---
title: cwoebker
author:
  email: me@cwoebker.com
  github: cwoebker
  name: "Cecil Woebker"
  twitter: cwoebker

auto: false
safe: false
server: false
server_port: 4000
base-url: /
production_url: "http://cwoebker.com"

source: .
destination: ./_site
plugins: ./_plugins
exclude:
  - README.md
  - util
  - drafts
  - config
  - Gemfile
  - Gemfile.lock
  - Procfile
  - Rakefile
  - vendor
  - config.ru

future: true
lsi: false
pygments: true
markdown: rdiscount
permalink: "/posts/:title"

rdiscount:
  extensions:
    - smart