safe: false
auto: false
server: false
server_port: 4000
base-url: /

source: .
destination: ./_site
plugins: ./_plugins

future: true
lsi: false
pygments: true
markdown: rdiscount 
permalink: /posts/:title

rdiscount:
    extensions: [smart]

title: cwoebker
production_url: http://cwoebker.com

author:
  name: Cecil Woebker
  email: me@cwoebker.com
  github: cwoebker
  twitter: cwoebker

exclude:
  - newpost.rb
  - kyll.py
  - Gemfile
  - Gemfile.lock
  - Procfile
  - vendor