--- 
author: 
  email: me@cwoebker.com
  github: cwoebker
  name: "Cecil Woebker"
  twitter: cwoebker
auto: false
base-url: /
destination: ./_site
exclude: 
  - newpost.rb
  - kyll.py
  - Gemfile
  - Gemfile.lock
  - Procfile
  - vendor
future: true
lsi: false
markdown: rdiscount
permalink: "/posts/:title"
plugins: ./_plugins
production_url: "http://cwoebker.com"
pygments: true
rdiscount: 
  extensions: 
    - smart
safe: false
server: false
server_port: 4000
source: "."
title: cwoebker