auto: true
safe: true
server: false
server_port: 4000
base-url: /

source: .
destination: ./_site
plugins: ./_plugins

future: true
lsi: false
pygments: true
markdown: rdiscount 
permalink: /posts/:title

title: cwoebker
production_url: http://cwoebker.com

rdiscount:
    extensions: [smart]

exclude:
  - newpost.rb
  - kyll.py
  - Gemfile
  - Gemfile.lock
  - Procfile

author:
  name: Cecil Woebker
  email: me@cwoebker.com
  github: cwoebker
  twitter: cwoebker
