auto: true
safe: true
pygments: true
markdown: rdiscount 
permalink: /posts/:title

title: cwoebker
production_url: http://cwoebker.com

rdiscount:
    extensions: [smart]

exclude:
  - newpost.rb
  - kyll.py

author:
  name: Cecil Woebker
  email: me@cwoebker.com
  github: cwoebker
  twitter: cwoebker
