safe: false
auto: true
server: false
server_port: 4000

source: .
destination: ./_site
plugins: ./_plugins

pygments: true
markdown: rdiscount 
permalink: /posts/:title

rdiscount:
    extensions: [smart]

exclude:
  - newpost.rb
